### ISSUE TITLE
Publishing older versions to NPM request

### ISSUE THREAD

**Issue by miloszes4** [jeremyckahn/shifty#184]
Hey,

Would it be possible to publish the older versions (shifty@0.6.1) to the NPM registry?

There’s probably more reasons others would like it on the registry, for us, we would be able to correctly attribute the project with the right credit and provide the right license information.

Thanks

**Comment by jeremyckahn** [comment]
Hi @miloszes4, thanks for raising this question. I believe that all the versions that are valid to publish to NPM are there. [Version 0.6.1](https://github.com/jeremyckahn/shifty/tree/b24b6e7b57ed188cab27b2b651d4a6f7d9569577) (which is 12 years old) doesn't have a `package.json` file, so NPM won't accept it. Would it be possible for you to upgrade to a newer version of Shifty? The oldest version available on NPM is [1.0.0](https://www.npmjs.com/package/shifty/v/1.0.0) (which is 10 years old). Upgrading to that would probably be the least amount of work for you, but I'd encourage you to upgrade to a more modern version as many things have improved since then.

I'm closing this for now because there's not much I have the capacity to do about this, but feel free to continue the conversation here.
