### ISSUE TITLE
Is calling dispose() mandatory?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [jeremyckahn/shifty#86]
Hi,

Is calling .dispose() mandatory when I no longer need the tweenable object? Shouldn't GC automatically remove the tweenable object when references to the tweenable are gone. E.g.:

```js

function tween() {
  var tweenable = new Tweenable();

  tweenable.tween({
    from: { a: 0 },
    to:   { a: 1 },
    duration: 500,
    easing: 'easeOutQuad',
    step: function(state) {
      // do stuff
    }
  });

  // tweenable should be cleaned after function call
}

tween()
```

**Comment by jeremyckahn** [comment]
Hi @kimmobrunfeldt, calling `dispose` is not mandatory, generally speaking.  I mainly added that method so that it could be inherited and overridden if necessary by objects that extend `Tweenable`.  I felt that a base object should provide some form of a cleanup method.  If removing it fixes https://github.com/kimmobrunfeldt/progressbar.js/issues/107, it should be safe to do so.

**Comment by kimmobrunfeldt** [comment]
Great, thanks for the quick reply!
