### ISSUE TITLE
Current browser compatibility?

### ISSUE THREAD

**Issue by donmccurdy** [jeremyckahn/shifty#88]
Which browsers are supported by shifty? I see that you've used a fallback for `requestAnimationFrame`, so I would assume that IE9 is safe... If that's the case it would be helpful to have this information included in the readme. Thanks!

**Comment by jeremyckahn** [comment]
Hi @donmccurdy, Shifty should support IE6 and up, as well as all modern browsers. I'll update the README when I get a moment!

**Comment by donmccurdy** [comment]
Great, thanks!

**Comment by jeremyckahn** [comment]
I haven't tested oldIE compatibility in quite a while, and it seems some tests are failing in my IE8 VM.  And, I can't even get my IE6 VM to run since it's been so long since I needed it, hah.  I'm assuming (perhaps unwisely, but confidently nonetheless) that IE9 is fine, because there probably would have been a bug reported by now if not.

I don't have an IE9 VM handy to test this with right now, so I will keep this open until I have properly tested it.  I do intend to support >IE9, so if you find a bug before I have a chance to test it, please report it here!

**Comment by jeremyckahn** [comment]
Well how about that!  There was a bug that affected IE8 and 9.  Thank you for filing this issue, because I might not have found that otherwise.  A fix has been made and released in [1.5.3](https://github.com/jeremyckahn/shifty/releases/tag/1.5.3).  Please upgrade to ensure proper support for those older browsers, and sorry about the hassle!

**Comment by donmccurdy** [comment]
Awesome, thanks for looking into this! 🙂
